server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  jpa:
    show-sql: true # it is used to show the sql queries made against H2 database
    hibernate:
      ddl-auto: update # this is used to create a table if it doesn't exist
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true